### ISSUE TITLE
Initial State from Props

### ISSUE THREAD

**Issue by NHypothesis** [baronswindle/react-redux-ephemeral#2]
One thing I'm looking for, inspired by redux-react-local, is the ability to initialize the state of an "ephemeral" reducer from props. Thoughts?

**Comment by baronswindle** [comment]
I actually just ran into this exact use case at work this evening. This is something that definitely ought to be included in this library. After all, you can initialize component state using React component state - it's not great that you lose that ability when you use this library to manage local state. I'll try to get a PR together by this evening.

**Comment by NHypothesis** [comment]
Sweet, thank you. Looks like it was a fairly straightforward addition. Will attempt playing with this tomorrow, then report back on the experience.

**Comment by NHypothesis** [comment]
Good enough to merge, I do believe.
